# Generated by Django 3.2.11 on 2022-03-25 16:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('dose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dose_type', models.CharField(choices=[('mg', 'mg'), ('mg/g', 'mg/g'), ('mg/ml', 'mg/ml'), ('ml', 'ml')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateTimeField()),
                ('sex', models.CharField(choices=[('Samica', 'f'), ('Samiec', 'm')], max_length=6)),
                ('additional_information', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=22, unique=True, validators=[django.core.validators.MinLengthValidator(22)])),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('Wystawiona', 'w'), ('Zrealizowana', 'z'), ('Wygasla', 'wy'), ('Anulowana', 'a')], max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.owner')),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='klinika.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('species_name', models.CharField(max_length=255, unique=True)),
                ('additional_information', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_planned', models.DateTimeField()),
                ('visit_time', models.TimeField()),
                ('status', models.CharField(choices=[('Zaplanowana', 'z'), ('Odbyta', 'o'), ('Anulowana', 'a')], max_length=11)),
                ('note', models.TextField(null=True)),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='klinika.pet')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_time_treatment', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2022, 4, 8, 16, 26, 15, 946367))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionCure',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('sz.', 'sz'), ('ml', 'ml'), ('op', 'op'), ('lst', 'lst')], max_length=3)),
                ('cure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.cure')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klinika.species'),
        ),
    ]
